name       : haskell-http
version    : 4000.4.1
release    : 1
source     :
    - https://hackage.haskell.org/package/HTTP-4000.4.1/HTTP-4000.4.1.tar.gz : df31d8efec775124dab856d7177ddcba31be9f9e0836ebdab03d94392f2dd453
license    : BSD-3-Clause
component  : programming.haskell
summary    : The HTTP package supports client-side web programming in Haskell.
description: |
    The HTTP package supports client-side web programming in Haskell.
builddeps  :
    - ghc-devel
    - haskell-network-devel
    - haskell-network-uri-devel
rundeps    :
    - devel :
        - haskell-network-devel
        - haskell-network-uri-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
replaces   :
    - haskell-HTTP
