name       : haskell-HTTP
version    : 4000.3.11
release    : 5
source     :
    - https://hackage.haskell.org/package/HTTP-4000.3.11/HTTP-4000.3.11.tar.gz : fad22b39d8027107158407a3af73907dbb66e403d9aa7b9fd778db171c65b645
license    : BSD-3-Clause
component  : programming.haskell
summary    : The HTTP package supports client-side web programming in Haskell.
description: |
    The HTTP package supports client-side web programming in Haskell.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-mtl
    - haskell-network
    - haskell-network-uri
    - haskell-parsec
setup      : |
    sed -i "s|< 2.7|<= 2.7|g" HTTP.cabal
    sed -i "s|network == 2.6.*|network == 2.7.*|g" HTTP.cabal
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
