name       : haskell-HTTP
version    : 4000.3.3
release    : 4
source     :
    - http://hackage.haskell.org/package/HTTP-4000.3.3/HTTP-4000.3.3.tar.gz : bbada3c2088dc1384234cdbc1bb6089ea588da068a6a38878ea259dd19de9bf2
license    : BSD-3-Clause
component  : programming.haskell
summary    : The HTTP package supports client-side web programming in Haskell.
description: |
    The HTTP package supports client-side web programming in Haskell.
builddeps  :
    - ghc
    - haskell-cabal-install
    - haskell-mtl
    - haskell-network
    - haskell-network-uri
    - haskell-parsec
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
