name       : haskell-HTTP
version    : 4000.3.3
release    : 2
source     :
    - http://hackage.haskell.org/package/HTTP-4000.3.3/HTTP-4000.3.3.tar.gz : bbada3c2088dc1384234cdbc1bb6089ea588da068a6a38878ea259dd19de9bf2
license    : BSD-3-Clause
component  : programming
summary    : The HTTP package supports client-side web programming in Haskell.
description: |
    The HTTP package supports client-side web programming in Haskell.
builddeps  :
    - ghc
    - haskell-mtl
    - haskell-network
    - haskell-network-uri
    - haskell-parsec
setup      : |
    sudo ghc-pkg recache
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 HTTP-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/HTTP-$version.conf
